/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ASOULCursors: typeof import('./src/components/projects/asoul-cursors/ASOULCursors.vue')['default']
    BilibiliJustListening: typeof import('./src/components/projects/bilibili-just-listening/BilibiliJustListening.vue')['default']
    CandiesVue: typeof import('./src/components/projects/candies/CandiesVue.vue')['default']
    ChocoberryVue: typeof import('./src/components/projects/chocoberry/ChocoberryVue.vue')['default']
    ChocolaTimer: typeof import('./src/components/projects/chocola-timer/ChocolaTimer.vue')['default']
    CocoaVue: typeof import('./src/components/projects/cocoa/CocoaVue.vue')['default']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTag: typeof import('element-plus/es')['ElTag']
    ExcelColumnSplitter: typeof import('./src/components/projects/excel-column-splitter/ExcelColumnSplitter.vue')['default']
    GeneticAlgorithmFunction: typeof import('./src/components/projects/genetic-algorithm-function/GeneticAlgorithmFunction.vue')['default']
    IFrameCell: typeof import('./src/components/projects/IFrameCell.vue')['default']
    LayerAnything: typeof import('./src/components/projects/layer-anything/LayerAnything.vue')['default']
    MarkdownCell: typeof import('./src/components/projects/MarkdownCell.vue')['default']
    MouseHalo: typeof import('./src/components/projects/mouse-halo/MouseHalo.vue')['default']
    MyProject: typeof import('./src/components/projects/MyProject.vue')['default']
    NoneOfAzureKinect: typeof import('./src/components/projects/none-of-azure-kinect/NoneOfAzureKinect.vue')['default']
    OneNoteObjectModel: typeof import('./src/components/projects/onenote-object-model/OneNoteObjectModel.vue')['default']
    OneNoteTagGUI: typeof import('./src/components/projects/onenote-tag-gui/OneNoteTagGUI.vue')['default']
    PaddyDoctor: typeof import('./src/components/projects/paddy-doctor/PaddyDoctor.vue')['default']
    PCodeViewer: typeof import('./src/components/projects/pcode-viewer/PCodeViewer.vue')['default']
    PL00WebIDE: typeof import('./src/components/projects/pl00-webide/PL00WebIDE.vue')['default']
    ProjectSummary: typeof import('./src/components/projects/ProjectSummary.vue')['default']
    PythonTutorial: typeof import('./src/components/projects/python-tutorial/PythonTutorial.vue')['default']
    RainVue: typeof import('./src/components/projects/rain/RainVue.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SDWebUIWebSocket: typeof import('./src/components/projects/sd-webui-websocket/SDWebUIWebSocket.vue')['default']
    TSPAPP: typeof import('./src/components/projects/tsp-app/TSPAPP.vue')['default']
    UnderwaterFishSystem: typeof import('./src/components/projects/underwater-fish-system/UnderwaterFishSystem.vue')['default']
    VideoCell: typeof import('./src/components/projects/VideoCell.vue')['default']
    XyqlxChannel: typeof import('./src/components/projects/xyqlx-channel/XyqlxChannel.vue')['default']
  }
}
